// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADpyN9eaCSSfTkWzEZJf_13AOEBS3A49E',
    appId: '1:837923389532:web:072f45606e5d7b45162699',
    messagingSenderId: '837923389532',
    projectId: 'cabtale-4f2d2',
    authDomain: 'cabtale-4f2d2.firebaseapp.com',
    storageBucket: 'cabtale-4f2d2.firebasestorage.app',
    measurementId: 'G-WMFQRX65NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEiHQnHLBnOqJKCmd8PVSyLlyRxwHIig',
    appId: '1:837923389532:android:93dc6bf38958cf74162699',
    messagingSenderId: '837923389532',
    projectId: 'cabtale-4f2d2',
    storageBucket: 'cabtale-4f2d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1b3HL60IHIEnP-6oYffWggfrnzAzfCU0',
    appId: '1:837923389532:ios:ffdda0b128462d56162699',
    messagingSenderId: '837923389532',
    projectId: 'cabtale-4f2d2',
    storageBucket: 'cabtale-4f2d2.firebasestorage.app',
    iosClientId: '837923389532-ni8hljfpo3hd7oj8em4jm5mulqh44729.apps.googleusercontent.com',
    iosBundleId: 'com.cabtale.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1b3HL60IHIEnP-6oYffWggfrnzAzfCU0',
    appId: '1:837923389532:ios:cb7e2ac2670759ca162699',
    messagingSenderId: '837923389532',
    projectId: 'cabtale-4f2d2',
    storageBucket: 'cabtale-4f2d2.firebasestorage.app',
    iosClientId: '837923389532-iukjmcaeo3ofukhcn738jkhgsp0en363.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADpyN9eaCSSfTkWzEZJf_13AOEBS3A49E',
    appId: '1:837923389532:web:0376bec9c3b6b329162699',
    messagingSenderId: '837923389532',
    projectId: 'cabtale-4f2d2',
    authDomain: 'cabtale-4f2d2.firebaseapp.com',
    storageBucket: 'cabtale-4f2d2.firebasestorage.app',
    measurementId: 'G-PN89HCR54B',
  );

}